
name: clvision24
channels:
- conda-forge
- pytorch
- nvidia
dependencies:
- pip
- typing_extensions==4.4.0
- python=3.10
- pytorch::pytorch>=2.0
- pytorch::pytorch-cuda>=11.8
- pip:
    - avalanche-lib==0.4.0